### ISSUE TITLE
Add `pulumi stack output` orb to introduce new CircleCI variable

### ISSUE THREAD

**Issue by chrsmith** [pulumi/circleci#15]
The `pulumi stack output` command prints the "outputs" of the currently selected stack.

For example (with some censoring):

```
$ pulumi stack output
Current stack outputs (8):
    OUTPUT                     VALUE
    albDnsName                 alb-xxx-xxx.us-xxx-1.elb.amazonaws.com
    apiServiceName             api--xxx
    apiServiceRepoUrl          xxx.dkr.ecr.us-xxx-2.amazonaws.com/api-repo-xxx
    autoScalingGroupStackName  autoScalingGroupStack-d691f8c
    consoleServiceRepoUrl      xxx.dkr.ecr.us-xxx-2.amazonaws.com/xxx
    databaseClusterEndpoint    tf-201910xxx.cluster-xxx.us-xxx-1.rds.amazonaws.com
    databaseClusterId          tf-2019xxxxx
    ecsClusterName             chris--xxx

$ pulumi stack output "apiServiceRepoUrl"
xxx.dkr.ecr.us-xxx-2.amazonaws.com/xxx
```

This is primarily used to automate/script things based on a stack. For example, running tests against the stack's API endpoint. Or copying data to a database or something.

Adding an orb like this would be super useful, especially if it could be used to _introduce_ or _declare_ some variable in the CircleCI configuration.

i.e. the equivalent of:
`export TEST_URL=$(pulumi stack output "apiEndpointUrl")`

See documentation for the commands at:
https://www.pulumi.com/docs/reference/cli/pulumi_stack_output/

**Comment by kenfdev** [comment]
I'll take this 👍

**Comment by kenfdev** [comment]
hmm... I'm wondering how this orb can be used. Your example from #14 about a review_app is as follows:

```yaml
review_app_example:
    description:
         "Creates a new Pulumi stack and deploys the source code built as part of the workflow, running
           tests against it. When complete, tears down the stack and cleans up any cloud resources."
    usage:
        ...
    steps:
        - checkout
        - build # ?
        - pulumi/login
        - pulumi/stack_init:
            stack: robot-co/test-pr_<< include CircleCI job number? >>
        - pulumi/stack_update
        - # export TEST_URL=$(pulumi stack output "awsLambdaUrl")?
        - run_tests $TEST_URL
      on_complete:
          - pulumi/destroy
          - pulumi/stack_rm:
              stack: << include CircleCI job number? >>
```

Assuming this orb will be called `pulumi/stack_output`, how would one use the output for further jobs?

Will it be something like this?

```yaml
pulumi/stack_output
  property_name: foo
  set_env_var: FOO
```
